# Site settings
title: A number of small steps down a road
email: neil@fauna.io
description: "Far from organized, possibly wrong."
baseurl: "/status"
url: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
